[package]
name = "cargo-dist-schema"
description = "Schema information for cargo-dist's dist-manifest.json"
version = "0.15.1"
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/axodotdev/cargo-dist"
exclude = [
  "book/*",
  "src/snapshots/*",
  "src/tests/",
  "tests/",
]

[dependencies]
camino = "1.1.7"
schemars = "0.8.21"
semver = "1.0.23"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
gazenot = { git = "https://github.com/axodotdev/gazenot.git", branch = "axoasset_fix_version", default-features = false }

[dev-dependencies]
insta = "1.39.0"
